alias dot='cd "$DOTFILES_DIR"'
alias reload!='exec zsh'
alias zshconfig='${EDITOR:-vim} ~/.zshrc'
alias dotconfig='${EDITOR:-vim} "$DOTFILES_DIR"'

alias gs='git status --short --branch'
alias gst='git status'
alias gap='git add -p'
alias gcam='git commit -am'
alias gfix='git commit --amend --no-edit'
alias gps='git push origin HEAD'
alias gpl='git pull --ff-only'
alias gpr='git pull --rebase'
alias gco='git checkout'
alias gsw='git switch'

alias pgstart='brew services start postgresql@16'
alias pgstop='brew services stop postgresql@16'
alias pgstatus='brew services info postgresql@16'
